### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Antidotas** [ArubikU/ItemsAdderCropSystem#1]
[11:40:53 INFO]: Antidotas issued server command: /ia
[11:41:35 INFO]: Antidotas issued server command: /i bone_meal
[11:41:58 INFO]: Antidotas issued server command: /i bone_meal
[11:46:54 FATAL]: Thread Craft Scheduler Thread - 63 - IACroper failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2291) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getNMSEntities(CraftWorld.java:987) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.getEntitiesByClass(CraftRegionAccessor.java:412) ~[patched_1.17.1.jar:git-Paper-409]
        at dev.arubik.iacs.events.newForChunks.lambda$0(newForChunks.java:18) ~[IACroper.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at dev.arubik.iacs.events.newForChunks.run(newForChunks.java:16) ~[IACroper.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-409]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-409]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[11:46:54 WARN]: [IACroper] Plugin IACroper v2.1.0 generated an exception while executing task 65
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2291) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getNMSEntities(CraftWorld.java:987) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.getEntitiesByClass(CraftRegionAccessor.java:412) ~[patched_1.17.1.jar:git-Paper-409]
        at dev.arubik.iacs.events.newForChunks.lambda$0(newForChunks.java:18) ~[IACroper.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at dev.arubik.iacs.events.newForChunks.run(newForChunks.java:16) ~[IACroper.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-409]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-409]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[11:48:10 INFO]: Antidotas issued server command: /ia
[11:49:24 INFO]: Antidotas issued server command: /ia
[11:56:34 INFO]: Antidotas issued server command: /killall mobs
[11:56:36 INFO]: Antidotas issued server command: /vanish
[11:56:39 INFO]: Antidotas issued server command: /time day
[11:57:44 FATAL]: Thread Craft Scheduler Thread - 48 - IACroper failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2291) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getNMSEntities(CraftWorld.java:987) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.getEntitiesByClass(CraftRegionAccessor.java:412) ~[patched_1.17.1.jar:git-Paper-409]
        at dev.arubik.iacs.events.newForChunks.lambda$0(newForChunks.java:18) ~[IACroper.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at dev.arubik.iacs.events.newForChunks.run(newForChunks.java:16) ~[IACroper.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-409]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-409]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[11:57:44 WARN]: [IACroper] Plugin IACroper v2.1.0 generated an exception while executing task 54246
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2291) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getNMSEntities(CraftWorld.java:987) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.getEntitiesByClass(CraftRegionAccessor.java:412) ~[patched_1.17.1.jar:git-Paper-409]
        at dev.arubik.iacs.events.newForChunks.lambda$0(newForChunks.java:18) ~[IACroper.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at dev.arubik.iacs.events.newForChunks.run(newForChunks.java:16) ~[IACroper.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-409]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-409]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[12:05:54 INFO]: [AsyncWorldEdit] Undo cleanup started...
[12:05:54 INFO]: [AsyncWorldEdit]        * plugins\AsyncWorldEdit\undo\1055a66b-b6e5-3a4e-a92f-f24a5dadffc1\ts.181b8888e39.d5b17366.0...ok
[12:05:54 INFO]: [AsyncWorldEdit]        * plugins\AsyncWorldEdit\undo\1055a66b-b6e5-3a4e-a92f-f24a5dadffc1\ts.181b8888e39.d5b17366.0.idx...ok
[12:05:54 INFO]: [AsyncWorldEdit] ...undo cleanup done.
[12:06:04 INFO]: [CustomCrafting] Saving Cauldrons
[12:08:34 FATAL]: Thread Craft Scheduler Thread - 104 - IACroper failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2291) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getNMSEntities(CraftWorld.java:987) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.getEntitiesByClass(CraftRegionAccessor.java:412) ~[patched_1.17.1.jar:git-Paper-409]
        at dev.arubik.iacs.events.newForChunks.lambda$0(newForChunks.java:18) ~[IACroper.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at dev.arubik.iacs.events.newForChunks.run(newForChunks.java:16) ~[IACroper.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-409]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-409]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[12:08:34 WARN]: [IACroper] Plugin IACroper v2.1.0 generated an exception while executing task 107671
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2291) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getNMSEntities(CraftWorld.java:987) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.getEntitiesByClass(CraftRegionAccessor.java:412) ~[patched_1.17.1.jar:git-Paper-409]
        at dev.arubik.iacs.events.newForChunks.lambda$0(newForChunks.java:18) ~[IACroper.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at dev.arubik.iacs.events.newForChunks.run(newForChunks.java:16) ~[IACroper.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-409]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-409]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[12:19:24 FATAL]: Thread Craft Scheduler Thread - 106 - IACroper failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2291) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getNMSEntities(CraftWorld.java:987) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.getEntitiesByClass(CraftRegionAccessor.java:412) ~[patched_1.17.1.jar:git-Paper-409]
        at dev.arubik.iacs.events.newForChunks.lambda$0(newForChunks.java:18) ~[IACroper.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at dev.arubik.iacs.events.newForChunks.run(newForChunks.java:16) ~[IACroper.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-409]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-409]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[12:19:24 WARN]: [IACroper] Plugin IACroper v2.1.0 generated an exception while executing task 161687
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2291) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getNMSEntities(CraftWorld.java:987) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.getEntitiesByClass(CraftRegionAccessor.java:412) ~[patched_1.17.1.jar:git-Paper-409]
        at dev.arubik.iacs.events.newForChunks.lambda$0(newForChunks.java:18) ~[IACroper.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at dev.arubik.iacs.events.newForChunks.run(newForChunks.java:16) ~[IACroper.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-409]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-409]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[12:21:59 INFO]: Antidotas issued server command: /ia
[12:30:14 FATAL]: Thread Craft Scheduler Thread - 133 - IACroper failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2291) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getNMSEntities(CraftWorld.java:987) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.getEntitiesByClass(CraftRegionAccessor.java:412) ~[patched_1.17.1.jar:git-Paper-409]
        at dev.arubik.iacs.events.newForChunks.lambda$0(newForChunks.java:18) ~[IACroper.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at dev.arubik.iacs.events.newForChunks.run(newForChunks.java:16) ~[IACroper.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-409]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-409]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[12:30:14 WARN]: [IACroper] Plugin IACroper v2.1.0 generated an exception while executing task 215426
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2291) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.getNMSEntities(CraftWorld.java:987) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.CraftRegionAccessor.getEntitiesByClass(CraftRegionAccessor.java:412) ~[patched_1.17.1.jar:git-Paper-409]
        at dev.arubik.iacs.events.newForChunks.lambda$0(newForChunks.java:18) ~[IACroper.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at dev.arubik.iacs.events.newForChunks.run(newForChunks.java:16) ~[IACroper.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-409]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-409]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
> iazip
[12:30:21 INFO]: [ItemsAdder] [Pack] Extracting utility resource_pack assets from .jar
[12:30:21 INFO]: [ItemsAdder] [Pack] DONE extracting utility resource_pack assets from .jar
[12:30:24 INFO]: [ItemsAdder] Loaded 747 items
[12:30:24 INFO]: [ItemsAdder] Used 4/188 REAL block IDs
[12:30:24 INFO]: [ItemsAdder] Used 33/750 REAL_NOTE block IDs
[12:30:24 INFO]: [ItemsAdder] Used 8/63 REAL_TRANSPARENT block IDs
[12:30:24 INFO]: [ItemsAdder] Used 108/127 REAL_WIRE block IDs
[12:30:24 INFO]: [ItemsAdder] Used 0/14 FIRE block IDs
[12:30:24 INFO]: [ItemsAdder] Used 931/6608 font_images
[12:30:24 INFO]: [ItemsAdder] [Init] Loaded 4 categories
[12:30:24 INFO]: [ItemsAdder] [Init] Loaded 747 items and stuff in 3131ms
[12:30:24 INFO]: [PlaceholderAPI] Successfully registered expansion: img [1.0.1]
[12:30:24 INFO]: [PlaceholderAPI] Successfully registered expansion: iaplayerstat [1.0.1]
[12:30:24 INFO]: [Mythic] Reloading plugin...
[12:30:24 INFO]: [MythicMobs] Mythic beginning reload procedure...
[12:30:24 INFO]: [MythicMobs] Loading Packs...
[12:30:24 INFO]: [MythicMobs] Loading Items...
[12:30:24 INFO]: [MythicMobs] Loading Skills...
[12:30:24 INFO]: [MythicMobs] Loading Drop Tables...
[12:30:24 INFO]: [MythicMobs] Loading Random Spawns...
[12:30:24 INFO]: [MythicMobs] Loading Spawn Blocks...
[12:30:24 INFO]: [MythicMobs] ✓ Loaded 30 mobs.
[12:30:24 INFO]: [MythicMobs] ✓ Loaded 3 vanilla mob overrides.
[12:30:24 INFO]: [MythicMobs] ✓ Loaded 0 mob stacks.
[12:30:24 INFO]: [MythicMobs] ✓ Loaded 10 skills.
[12:30:24 INFO]: [MythicMobs] ✓ Loaded 2 random spawns.
[12:30:24 INFO]: [MythicMobs] ✓ Loaded 3 mythic items.
[12:30:24 INFO]: [MythicMobs] ✓ Loaded 2 drop tables.
[12:30:24 INFO]: [MythicMobs] ✓ Loaded 0 mob spawners.
[12:30:24 INFO]: [Mythic] Mythic has finished reloading!
[12:30:24 INFO]: [MythicMobs] Mythic has finished reloading!
[12:30:40 INFO]: [ItemsAdder] [OK] Your zip file will be protected from unzip (as set in config.yml)
[12:30:40 INFO]: [ItemsAdder] [Pack] Compressing resource_pack ...
[12:30:49 INFO]: [ItemsAdder] [Pack] Resource pack successfully compressed. Uploading...
[12:30:50 INFO]: [ItemsAdder] [Pack] Uploading resourcepack...
[12:31:09 INFO]: [ItemsAdder] [Pack] Finished uploading resourcepack: http://resourcepack.host/dl/16o6XWsytFTtKp9mehIUISao6J441u4y/pack.zip
[12:31:19 INFO]: [ItemsAdder] [Pack] Resourcepack URL is valid (auto-external-host), LastEdit: 2022-07-01_12-31. Url: http://resourcepack.host/dl/16o6XWsytFTtKp9mehIUISao6J441u4y/pack.zip
[12:31:19 INFO]: [ItemsAdder] Applying pack to every player...
[12:31:19 INFO]: [ItemsAdder] Applied pack to 1 players
[12:32:05 INFO]: Antidotas issued server command: /time day
[12:32:18 INFO]: Antidotas issued server command: /disposal
[12:32:32 INFO]: Antidotas issued server command: /ia
[12:33:54 ERROR]: Could not pass event PlayerInteractEntityEvent to IACroper v2.1.0
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.entity.CraftWanderingTrader cannot be cast to class org.bukkit.entity.ArmorStand (org.bukkit.craftbukkit.v1_17_R1.entity.CraftWanderingTrader and org.bukkit.entity.ArmorStand are in unnamed module of loader 'app')
        at dev.arubik.iacs.managers.newManagerIacrops$rightClickArmorStand.onPlayerClickOnFurniture(newManagerIacrops.java:84) ~[IACroper.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor492.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-409]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-409]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2427) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.onInteraction(ServerGamePacketListenerImpl.java:2477) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:131) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2419) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-409]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[12:34:52 INFO]: Antidotas issued server command: /ia
>

**Comment by ArubikU** [comment]
Can you send me our config file please

**Comment by Antidotas** [comment]
config:
  mythic-lib: true
  block-packets: true
  block-mode: true
  furniture-mode: true
  max-water: 40
  async-not-safe: false
  max-water-error: <gradient:blue:Maksimalus vazono dregnumas gali buti 40l arba 4 kibirai vandens</gradient>
  water-identifier-msg: <gradient:blue:aqua>Zemes dregnumas vazone instance:mb / cnf:config.max-water
    player:name </gradient>
  water-identifier: croper:identifier
  sprinkler: croper:sprinkler
  bone-meal: true
  bone-meal-percent: 10
  water_farming_station: croper:watered_farm
  farming_station: croper:farm
  water-default: true
  WATER_BUCKET: 10
  WATER_BOTTLE: 2
  items:
    croper:cantimplora_1: toItem:{toItem=croper:cantimplora;water=10}
    croper:cantimplora_2: toItem:{toItem=croper:cantimplora_1;water=10}
    croper:cantimplora_3: toItem:{toItem=croper:cantimplora_2;water=10}
    croper:cantimplora_4: toItem:{toItem=croper:cantimplora_3;water=10}
    croper:cantimplora_5: toItem:{toItem=croper:cantimplora_4;water=10}
  worlds:
  - world
  water-take: 2.5
  time-grow: 650
  events:
  - particle:{particle=WATER_SPLASH;amount=15;speed=0.1;offset_x=0.5;offset_y=1.6;offset_z=0.5;delay=5}
    ~OnAddWater
  - particle:{particle=WATER_SPLASH;amount=15;speed=0.1;offset_x=0.5;offset_y=1.5;offset_z=0.5;delay=4}
    ~OnAddWater
  - particle:{particle=WATER_SPLASH;amount=15;speed=0.1;offset_x=0.5;offset_y=1.4;offset_z=0.5;delay=3}
    ~OnAddWater
  - particle:{particle=WATER_SPLASH;amount=15;speed=0.1;offset_x=0.5;offset_y=1.3;offset_z=0.5;delay=2}
    ~OnAddWater
  - particle:{particle=WATER_SPLASH;amount=15;speed=0.1;offset_x=0.5;offset_y=1.2;offset_z=0.5;delay=1}
    ~OnAddWater
  - particle:{particle=WATER_SPLASH;amount=15;speed=0.1;offset_x=0.5;offset_y=1.1;offset_z=0.5;delay=0}
    ~OnAddWater
  - sound:{sound=ambient.underwater.enter;volume=2;pitch=1} ~OnAddWater
  - toItem:{toItem=croper:cantimplora_1;mainhand=croper:cantimplora} ~RightClickWater
  - toItem:{toItem=croper:cantimplora_2;mainhand=croper:cantimplora_1} ~RightClickWater
  - toItem:{toItem=croper:cantimplora_3;mainhand=croper:cantimplora_2} ~RightClickWater
  - toItem:{toItem=croper:cantimplora_4;mainhand=croper:cantimplora_3} ~RightClickWater
  - toItem:{toItem=croper:cantimplora_5;mainhand=croper:cantimplora_4} ~RightClickWater

**Comment by ArubikU** [comment]
Disable furniture mode
